# Generated by Django 5.0.6 on 2024-07-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmsapp.deptmodel')),
            ],
        ),
    ]
